### ISSUE TITLE
Orca crashes under KDE Plasma Wayland when slicer detailed model (NVIDIA PGU)

### ISSUE THREAD

**Issue by turw41th** [OrcaSlicer/OrcaSlicer#11722]
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.1

### Operating System (OS)

Linux

### OS Version

CachyOS

### Additional system information

OS: CachyOS x86_64
Kernel: Linux 6.18.2-2-cachyos
DE: KDE Plasma 6.5.4
WM: KWin (Wayland)
CPU: Intel(R) Core(TM) i9-10920X (24) @ 4.80 GHz
GPU: NVIDIA GeForce RTX 3080 Lite Hash Rate [Discrete]

### Printer

Qidi Plus 4

### How to reproduce

- Open detailed stl file (D&D miniature in my case) (24MB in size)
- Slice with high details (0.06mm layer height, 0.2mm nozzle
- Wait

### Actual results

At slicing layer 630 (which actually is the last layer), Orca freezes and then crashes. The last few lines in the console are
```
MESA: error: zink: couldn't allocate memory: heap=3 size=4194304
MESA: error: zink: couldn't allocate memory: heap=3 size=4194304
MESA: error: zink: couldn't allocate memory: heap=3 size=4194304
MESA: error: zink: couldn't allocate memory: heap=3 size=4194304
MESA: error: zink: couldn't allocate memory: heap=3 size=4194304
MESA: error: zink: couldn't allocate memory: heap=3 size=4194304
MESA: error: zink: couldn't allocate memory: heap=3 size=4194304
MESA: error: zink: couldn't allocate memory: heap=3 size=2097152
MESA: error: ZINK: vkMapMemory failed (VK_ERROR_MEMORY_MAP_FAILED)
[1]    346626 segmentation fault (core dumped)
```

This only happens under Wayland. On X11, slicing is perfectly fine.

Also, Orca crashes when I switch to the device tab, but that's another issue.

### Expected results

Model should slice without crashing.

### Project file & Debug log uploads

[Wayland-Crash.zip](https://github.com/user-attachments/files/24318674/Wayland-Crash.zip)
[coredump.txt](https://github.com/user-attachments/files/24318731/coredump.txt)

### Checklist of files to include

- [x] Log file
- [x] Project file

### Anything else?

Log files don't seem to be created when this crash occurs. I uploaded the core dump instead.

**Comment by Sorig2** [comment]
I made a github account to comment that I have the same exact issue. 
It happens while rendering the sliced model, it doesn't crash if you switch the tab to not see the sliced model and slices succesfuly, but crashes once you switch to see it again. No orca-slicer package on the aur fixes this, not even the appimage. I think the new nvidia 590 driver is to blame for these crashes as I don't remember this happening before. Orca slicer also crashes for me in the device tab, but I think that is unrelated as well.

**Comment by turw41th** [comment]
> I made a github account to comment that I have the same exact issue. 
> It happens while rendering the sliced model, it doesn't crash if you switch the tab to not see the sliced model and slices succesfuly, but crashes once you switch to see it again. No orca-slicer package on the aur fixes this, not even the appimage. I think the new nvidia 590 driver is to blame for these crashes as I don't remember this happening before. Orca slicer also crashes for me in the device tab, but I think that is unrelated as well.

Switching to X11 solved the issue so far that opening the device tab and rendering a sliced model doesn't crash orca anymore, now the Home and device tabs don't render anything anymore. I can live with that though, I just open the printers web interface in my browser. But no more crashes.

**Comment by renegadespork** [comment]
> I made a github account to comment that I have the same exact issue. It happens while rendering the sliced model, it doesn't crash if you switch the tab to not see the sliced model and slices succesfuly, but crashes once you switch to see it again. No orca-slicer package on the aur fixes this, not even the appimage. I think the new nvidia 590 driver is to blame for these crashes as I don't remember this happening before. Orca slicer also crashes for me in the device tab, but I think that is unrelated as well.

Thanks for the tip! It’s a janky workaround, but at least I can print. 

Seeing as the heap allocation fails at **exactly** 4MB, I suspect someone used the wrong integer type somewhere. 

Watching the logs, the memory allocation error occurs at the start of slicing, but the crash only occurs when it tries to reference that memory and render the preview. So… I guess you can avoid it by never looking at the preview… 💀

**Comment by wimgoeman** [comment]
Pretty sure this is a duplicate of #11698

**Comment by Mrtechit10121** [comment]
> Pretty sure this is a duplicate of [#11698](https://github.com/OrcaSlicer/OrcaSlicer/issues/11698)

Not a duplicate, fuzzy skin has nothing to do with it. And either way, this needs to get fixed so.... 

People like me, who have recently left windows need things to work smoothly to stay. I understand things arent always smooth, but others will most likely switch back to windows because of issues like this.

I also have this same issue. Also the device tab issue.

**Comment by TheAverageCanadian** [comment]
Same crash here, not a singular complex model, just a full print plate (15 tiny objects and 5 small to medium objects).
Previously I have sliced the same plate with no issues. Currently I can't print anything.

OS: Arch Linux x86_64
Kernel: 6.18.2-arch2-1
Desktop: KDE Plasma 6.5.4
GPU: Nvidia RTX 2070 Super
CPU: Intel i7-9700k
Memory: 32GB DDR4@3200MHz
Package (AUR): orca-slicer-git 2.3.2r25532.295758f-1

**Comment by bdunks** [comment]
@Mrtechit10121  - This also isn't related to KDE Plasma.

It's impacting Arch users who updated to Mesa 25.3.2 within the last 10 days, the same root cause for both issues.

@turw41th - You may want to consider closing this as duplicate of #11698, the slightly older issue with more details in the comments.  That way the community can throw their weight behind a single issue for better visibility.

**Comment by Mrtechit10121** [comment]
Now, if somehow mesa is the problem, it has had the problem for longer than 25.3.2. As again, this has impacted me for about 2 months (since beginning of February, roughly feb 10th when i switched to Arch)

OS: CachyOS x86_64
Kernel: Linux 6.18.2-2-cachyos
DE: KDE Plasma 6.5.4
WM: KWin (Wayland)
CPU: AMD Ryzen 7 5700X3D (16) @ 4.15 GHz
GPU: NVIDIA GeForce RTX 3090 [Discrete]
Memory: 11.99 GiB / 62.71 GiB (19%)

Edit: do not feel like fighting over this. Backing both instances of this issue, either way.

**Comment by bdunks** [comment]
Thanks for this clarification.  I've spent some time looking into this since your comment.  It's a pretty arduous process because every clean re-build (including dependencies) takes about 40 minutes on my older machine.  

I think there are at least two separate issues being conflated in one report: One that has been ongoing for some time, and another that has just started
 in the last 10-14 days.

It appears that at least a set of these issues are addressed with this recent PR, updating the GLFW library, which had a lot of Wayland fixes in a newer release than the one currently bundled: https://github.com/OrcaSlicer/OrcaSlicer/pull/11518

Despite spending nearly all day making small changes, and diagnostics, and rebuilding, no luck so far isolating the MESA issue.

**Comment by bdunks** [comment]
For those that aren't following both issues, I've added a [complete root cause analysis](https://github.com/OrcaSlicer/OrcaSlicer/issues/11698#issuecomment-3712023430) in #11698.

Bottom line, I believe the crashes will be fixed with #10735, and the remaining errors (which aren't causing crashes) have a path to closure.

**Comment by turw41th** [comment]
@bdunks Thank you very much for your efforts! Let's hope it will be merged soon.

**Comment by mCr86** [comment]
Hi,
I'm still having the same problem when the sliced model is very complex.
This does not occur in simple models.

**Comment by bdunks** [comment]
> Hi,
> I'm still having the same problem when the sliced model is very complex.
> This does not occur in simple models.

This PR above was merged into main. It's available in 2.3.2-dev if you run the nightly build.

**Comment by turw41th** [comment]
@bdunks Thanks for your contribution! I'm currently on the latest git version of Orca, a new issue has popped up when slicing complex models. 
```
/usr/include/c++/15.2.1/bits/stl_vector.h:1263: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = long int; _Alloc = std::allocator<long int>; reference = long int&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
[1]    21222 IOT instruction (core dumped)  orca-slicer
```
I don't know whether that has to do with the other issue discussed in this thread or if that's something new.

**Comment by bdunks** [comment]
@turw41th  - Sorry for not responding faster.  This doesn't _look_ related.  The prior errors were related to allocating memory between the CPU and GPU.  This seems to be some other assertion failure.  

I'm really not a C++ developer (or Orca maintainer).  I hadn't debugged C++ in at least 5 years.  Sorry I can't be more helpful.
