### ISSUE TITLE
create printer - some vendors are not found

### ISSUE THREAD

**Issue by HAndreasH** [OrcaSlicer/OrcaSlicer#5499]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.1.0-alpha

### Operating System (OS)

Windows

### OS Version

Win 11

### Printer

Ender 3 pro

### How to reproduce

create printer/nozzle dialog
some vendors are not selectable
noticed it by selecting Creality

![Screenshot 2024-05-29 164236](https://github.com/SoftFever/OrcaSlicer/assets/98119968/af6222e2-ac0d-475d-afcd-881d35d430f9)

### Actual results

error message: The model was not found; please reselect vendor.

### Expected results

select model from vendor

### Project file & Debug log uploads

[debug_Wed_May_29_16_44_26_17932.log.zip](https://github.com/SoftFever/OrcaSlicer/files/15487640/debug_Wed_May_29_16_44_26_17932.log.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by HAndreasH** [comment]
just tested in V2.1.0-beta, same result

**Comment by bistory** [comment]
Same issue with Bambulab, Comgrow, "Custom Printer", Elegoo, Flashforge, FlyingBear, Folgertech, InfiMech, Kingroon, "Orca Arena Printer", Peopoly, Prusa, Qidi, Raise3D, SecKit, Tronxy, Twotrees, UltiMaker, Vivedino, Voxelab, Vzbot and Wanhao printers.
I guess there is something missing in the profiles.

**Comment by HAndreasH** [comment]
still not working in V2.1.0-rc

**Comment by Highcooley** [comment]
Same on Linux. Checking the template Folder, e.g. Bambulab folder is completely missing.

**Comment by rkaneknight** [comment]
I'm seeing the same issue.  If anyone else sees this when searching for a solution, I found that I can still add an additional printer if I click on the left side printer dropdown and "Select/Remove Printers (system presets)".  At least this dialog works as expected.

**Comment by duesk** [comment]
same on Mac

**Comment by Roofstalker** [comment]
Same issue on Win 11

**Comment by HAndreasH** [comment]
> I'm seeing the same issue. If anyone else sees this when searching for a solution, I found that I can still add an additional printer if I click on the left side printer dropdown and "Select/Remove Printers (system presets)". At least this dialog works as expected.

something seems to be wrong here with database query
i think we have to be patient until someone finds the time to fix the problem
until then we can easily use the work around

**Comment by shnlmn** [comment]
Just downloaded OrcaSlicer_Windows_Installer_V2.1.1.exe and am having the exact same issue.

**Comment by HAndreasH** [comment]
However, the bug has still not been fixed in the current developer build.
You can of course add printers as described in the previous [comment from rkaneknight](https://github.com/SoftFever/OrcaSlicer/issues/5499#issuecomment-2212608757) already

**Comment by Stormwing01** [comment]
Still not fixed

**Comment by rtm7777** [comment]
Tried to connect bambu for the first time, same issue

**Comment by LukasExemplar** [comment]
Same issue.

**Comment by octico** [comment]
Bug still persists in 2.2.0 
![image](https://github.com/user-attachments/assets/1e74aea1-4e22-4e45-80fc-98d4aa8e680d)

![image](https://github.com/user-attachments/assets/abded97a-d646-4b28-88ef-470ca8e09330)

**Comment by octico** [comment]
> I'm seeing the same issue. If anyone else sees this when searching for a solution, I found that I can still add an additional printer if I click on the left side printer dropdown and "Select/Remove Printers (system presets)". At least this dialog works as expected.

Confirmed this workaround is valid.

**Comment by idoraz1** [comment]
hey guys! just solved it!. i am using orca slicer 2.1.0
choose "Select/Remove Printers (system presets)" then add the printer you want and then close and open orca. 
now the printer profile should be available.
 
![image](https://github.com/user-attachments/assets/c2a6146e-fd38-4068-a547-cdf1f7db95c6)
![image](https://github.com/user-attachments/assets/6e349429-b05e-474a-a1ac-8ef5dea35006)

**Comment by MetonIvictus** [comment]
I am having the same issue, i cannot use orca untill this is fixed. Any ETA on the fix?

**Comment by idoraz1** [comment]
> I am having the same issue, i cannot use orca untill this is fixed. Any ETA on the fix?

Look one comment up bro...

**Comment by MetonIvictus** [comment]
> > I am having the same issue, i cannot use orca untill this is fixed. Any ETA on the fix?
> 
> Look one comment above bro...

This does not work for me, i have tried this before i posted.

**Comment by ignis32** [comment]
version 2.3

Looks like that bug is still there.


Cannot create a printer with non standard nozzle because of that.

**Comment by HAndreasH** [comment]
confirm, the bug is still present

![Image](https://github.com/user-attachments/assets/36a04fee-867e-4574-aabc-06fcc03377c7)

**Comment by homeland3d** [comment]
This bug is always present on 2.3 release fresh install --> create new printer --> select bambulab from producer and than come up the pop-up tell the model is not found for this producer please re-select the producer. Sorry my screen is in italian if you need I'll create in english with version 2.3

**Comment by drakeg77** [comment]
2.3 release crashes when you click "select/remove printer"
the same issue occurs when trying to add custom printers and bambu

**Comment by clutter16** [comment]
I found a working fix - at least for me
Uninstall OrcaSlicer (if you have saved files just save them in a separate folder)
Go to Program Files and delete the OrcaSlicer folder
Go to AppData (Local AND Roaming) and delete the OrcaSlicer folders for each
Run a clean install and everything should be fine.

**Comment by RMatGitHub** [comment]
> I found a working fix - at least for me Uninstall OrcaSlicer (if you have saved files just save them in a separate folder) Go to Program Files and delete the OrcaSlicer folder Go to AppData (Local AND Roaming) and delete the OrcaSlicer folders for each Run a clean install and everything should be fine.

This did not work....

**Comment by anmolbyte** [comment]
still having this issue, windows 10

**Comment by theDCM** [comment]
still having this issue
windows 10

**Comment by TerseHickory** [comment]
Still having this issue

**Comment by idoraz1** [comment]
> hey guys! just solved it!. i am using orca slicer 2.1.0 choose "Select/Remove Printers (system presets)" then add the printer you want and then close and open orca. now the printer profile should be available.
> 
> ![image](https://github.com/user-attachments/assets/c2a6146e-fd38-4068-a547-cdf1f7db95c6) ![image](https://github.com/user-attachments/assets/6e349429-b05e-474a-a1ac-8ef5dea35006)

That's not working anymore? (Question mark) 
Try to do this on a fresh installation.

**Comment by barmanr** [comment]
Tried this today with 2.4.0-dev and I am unable to reproduce this on Win 11 and Mac. I was able to select the model fine.

**Comment by PorcelainMouse** [comment]
I still get this error on Linux with nightly build in flatpak.  I tried it just last night.  It's not all vendors, but BambuLab is one of them for which I get this error.

One the other hand, now I can't do anything without it crashing.  Last night, I uninstalled it and cleaned the whole directory, installed it, and started over.  That seemed to help, but now it's back to being really crash-y.

**Comment by PorcelainMouse** [comment]
Update: I built my own from src. That binary is much more reliable, faster too.  Thank you to the OrcaSlicer team for making good OSS, even if you aren't hosting pre-built RPM pkgs.  You rock, many thanks.

**Comment by PorcelainMouse** [comment]
Oh, but I still have this bug!  I cannot create a new printer from BBL template because I get there error that the template doesn't exist, even though I can select it from the pull down menu.

**Comment by BertrandTheHealer** [comment]
Still experiencing this issue in 2.4.0-alpha. Clearing program data / app data and reinstalling does not fix it.
